
genesis-file="genesis.json"
node-private-key-file="nodes/node1/config/nodekey"
logging="INFO"
data-path="nodes/node1/data"
host-allowlist=["*"]
min-gas-price=0

# rpc
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]

# ws
rpc-ws-enabled=true
rpc-ws-host="0.0.0.0"
rpc-ws-port=8546

# metrics
metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port=9545

# bootnodes
bootnodes=["enode://8208a3f344695d44e9cf2c023683cbea7b9343e2f70a5e804bd2c93858e945f8f91439eef96a4ab6c47ff06637d6fbe6472f96de1655a1bee57ea896654f3a22@docker.for.mac.localhost:30301"]
discovery-enabled=true
