---
version: '3.6'

services:

  blockscout:
    image: consensys/blockscout:v4.1.7
    container_name: blockscout
    restart: "no"
    environment:
      - PORT=4000
      - ECTO_USE_SSL=false
      - DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/postgres?ssl=false
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - NETWORK=quickstart
      - NETWORK=Dev Quickstart
      - SUBNETWORK=Quorum
      - CHAIN_ID=1337
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=besu
      - ETHEREUM_JSONRPC_TRANSPORT=http
      - ETHEREUM_JSONRPC_HTTP_URL=http://host.docker.internal:22001
      - ETHEREUM_JSONRPC_TRACE_URL=http://host.docker.internal:22001
      - ETHEREUM_JSONRPC_WS_URL=ws://host.docker.internal:23001
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /opt/app/;
        echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
    depends_on:
      - blockscoutpostgres
    links:
      - blockscoutpostgres
    ports:
      - 26000:4000

  blockscoutpostgres:
    platform: linux/arm64
    image: postgres:13.6-alpine
    restart: "on-failure"
    container_name: blockscoutpostgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - blockscoutpostgres:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
   
volumes:
  blockscoutpostgres: